### PR TITLE
extract-post-file bug fixed, typos and spelling fixed, tests added

### PR DESCRIPTION
**Pull request by kt97679**

### CODE REVIEW

**Review by sjafferali — COMMENTED** [review]
@kt97679, lgtm Would you bump the version a minor release as well?

**Comment by kt97679** [comment]
Thanks a bunch for the quick review @sjafferali ! Yes, you are absolutely right, minor release should be incremented, did this in the latest commit.

**Review by sjafferali — APPROVED** [review]
Thanks for the change.

**Comment by kt97679** [comment]
Thanks @sjafferali ! I'm afraid I can't merge because I have no write access. May I ask you to merge for me?

**Comment by sjafferali** [comment]
> Thanks @sjafferali ! I'm afraid I can't merge because I have no write access. May I ask you to merge for me?

Sure, I will merge this tomorrow.

**Comment by kt97679** [comment]
Awesome :)! Thanks!

**Comment by sjafferali** [comment]
@kt97679 Would you bump the version once more. There was another change that was merged in to sync this version with our internal version https://github.com/hulu/urepo/pull/7 . Thanks!

**Comment by kt97679** [comment]
done :)

**Pull request merged**
